site_name: AWARENET
site_url: https://<tuo-utente>.github.io/AWARENET_website/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
nav:
  - Home: index.md
  - Chi siamo: about.md
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
